### ISSUE TITLE
[Bug]: IllegalStateException on /updatemapstyle

### ISSUE THREAD

**Issue by nono303** [telemaxx/mapsforgesrv#58]
### What happened?

hi @telemaxx !
Just a quick fix to avoid IllegalStateException on /updatemapstyle
```patch
diff --git "a/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java" "b/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java"
index 7d32864..4a5736d 100644
--- "a/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java"
+++ "b/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java"
@@ -412,11 +412,11 @@ public class MapsforgeHandler extends AbstractHandler {
 
 			if (path.equals("/updatemapstyle")) { //$NON-NLS-1$
 				updateRenderThemeFuture();
-				try (ServletOutputStream out = response.getOutputStream();) {
-					out.print("<html><body><h1>updatemapstyle</h1>OK</body></html>"); //$NON-NLS-1$
-					out.flush();
-				}
-				response.sendError(HttpServletResponse.SC_OK);
+				response.setHeader("Cache-Control", "private, no-cache");
+				response.setHeader("Pragma", "no-cache");
+				response.setContentType("text/html;charset=utf-8");
+				response.setStatus(HttpServletResponse.SC_OK);
+				baseRequest.setHandled(true);
+				response.getWriter().println("<html><body><h1>updatemapstyle</h1>OK</body></html>");
+				response.flushBuffer();
 				return;
 			}
 ```

### Version

Java 11 Branch(Default)

### Relevant log output

```shell
2024-04-25 08:59:06.026 queue-67@HttpChannel:797 - /updatemapstyle
java.lang.IllegalStateException: COMPLETED
        at org.eclipse.jetty.server.HttpChannelState.sendError(HttpChannelState.java:911)
        at org.eclipse.jetty.server.Response.sendError(Response.java:501)
        at com.telemaxx.mapsforgesrv.MapsforgeHandler.handle(MapsforgeHandler.java:596)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by JFritzle** [comment]
Fixed and successfully tested with version 0.21.1

**Comment by telemaxx** [comment]
when i run copyFatJar2jars_ready2use,
i got an error:

![grafik](https://github.com/telemaxx/mapsforgesrv/assets/22706487/6339d074-6a47-4bc8-85c3-58eb227737c8)


when i change back to jetty 11 its ok.

    def jettyVersion = '12.0.8'
    //def jettyVersion = '11.0.20'

how to solve?

**Comment by telemaxx** [comment]
i also tried this:

`testImplementation 'org.eclipse.jetty.http2:jetty-http2-server:${jettyVersion}'`

**Comment by nono303** [comment]
Same for me: choice 2 (https://github.com/nono303/mapsforgesrv/blob/master/mapsforgesrv/build.gradle#L30)

**Comment by telemaxx** [comment]
for me i also choice 2.
makes the life easier.

**Comment by JFritzle** [comment]
Already created a pull request.

**Comment by telemaxx** [comment]
perfect

**Comment by nono303** [comment]
Hi @telemaxx @JFritzle 
merged https://github.com/telemaxx/mapsforgesrv/commit/e05a9219047f228200c6d2190bea71368a35c584 
- build OK (no jetty deps error)
- checked both /terminate & /updatemapstyle: no more IllegalStateException

you might just tag https://github.com/telemaxx/mapsforgesrv/commit/e05a9219047f228200c6d2190bea71368a35c584  as `v0.21.1_for_java11` ;)

Many Thx for your actions!

**Comment by telemaxx** [comment]
@nono303 @JFritzle  the release v021.1_for_java 8 and 11 is made
